
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ashirvad.Repo.Model
{

using System;
    using System.Collections.Generic;
    
public partial class ABOUTUS_DETAIL_REL
{

    public long brand_id { get; set; }

    public long aboutus_id { get; set; }

    public string brand_name { get; set; }

    public byte[] header_img { get; set; }

    public int row_sta_cd { get; set; }

    public long trans_id { get; set; }



    public virtual ABOUTUS_MASTER ABOUTUS_MASTER { get; set; }

}

}
