
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ashirvad.Repo.Model
{

using System;
    using System.Collections.Generic;
    
public partial class ABOUTUS_MASTER
{

    public long aboutus_id { get; set; }

    public string website { get; set; }

    public string email_id { get; set; }

    public string contact_no { get; set; }

    public string whatsapp_no { get; set; }

    public long branch_id { get; set; }

    public string header_img_name { get; set; }

    public long trans_id { get; set; }

    public int row_sta_cd { get; set; }

    public string aboutus_desc { get; set; }

    public string header_img_path { get; set; }



    public virtual BRANCH_MASTER BRANCH_MASTER { get; set; }

}

}
