
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ashirvad.Repo.Model
{

using System;
    using System.Collections.Generic;
    
public partial class ANNOUNCE_MASTER
{

    public long announce_id { get; set; }

    public Nullable<long> branch_id { get; set; }

    public string announce_text { get; set; }

    public long trans_id { get; set; }

    public int row_sta_cd { get; set; }

}

}
