
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ashirvad.Repo.Model
{

using System;
    using System.Collections.Generic;
    
public partial class BRANCH_MAINT
{

    public long branch_id { get; set; }

    public byte[] branch_logo { get; set; }

    public byte[] header_logo { get; set; }

    public string website { get; set; }

    public string branch_logo_ext { get; set; }

    public string header_logo_ext { get; set; }

    public string file_path { get; set; }

    public string file_name { get; set; }



    public virtual BRANCH_MASTER BRANCH_MASTER { get; set; }

}

}
