
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ashirvad.Repo.Model
{

using System;
    using System.Collections.Generic;
    
public partial class BRANCH_MASTER
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public BRANCH_MASTER()
    {

        this.BATCH_MASTER = new HashSet<BATCH_MASTER>();

        this.BRANCH_LICENSE = new HashSet<BRANCH_LICENSE>();

        this.BRANCH_STAFF = new HashSet<BRANCH_STAFF>();

        this.SCHOOL_MASTER = new HashSet<SCHOOL_MASTER>();

        this.STD_MASTER = new HashSet<STD_MASTER>();

        this.STUDENT_MASTER = new HashSet<STUDENT_MASTER>();

        this.SUBJECT_MASTER = new HashSet<SUBJECT_MASTER>();

        this.GALLERY_MASTER = new HashSet<GALLERY_MASTER>();

        this.LINK_MASTER = new HashSet<LINK_MASTER>();

        this.PRACTICE_PAPER = new HashSet<PRACTICE_PAPER>();

        this.ATTENDANCE_HDR = new HashSet<ATTENDANCE_HDR>();

        this.TEST_MASTER = new HashSet<TEST_MASTER>();

        this.REMINDER_MASTER = new HashSet<REMINDER_MASTER>();

        this.STUDENT_ANS_SHEET = new HashSet<STUDENT_ANS_SHEET>();

        this.HOMEWORK_MASTER = new HashSet<HOMEWORK_MASTER>();

        this.TODO_MASTER = new HashSet<TODO_MASTER>();

        this.ABOUTUS_MASTER = new HashSet<ABOUTUS_MASTER>();

    }


    public long branch_id { get; set; }

    public string branch_name { get; set; }

    public Nullable<int> row_sta_cd { get; set; }

    public string about_us { get; set; }

    public string contact_no { get; set; }

    public string mobile_no { get; set; }

    public string email_id { get; set; }

    public long trans_id { get; set; }

    public int branch_type { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BATCH_MASTER> BATCH_MASTER { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BRANCH_LICENSE> BRANCH_LICENSE { get; set; }

    public virtual BRANCH_MAINT BRANCH_MAINT { get; set; }

    public virtual TRANSACTION_MASTER TRANSACTION_MASTER { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BRANCH_STAFF> BRANCH_STAFF { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SCHOOL_MASTER> SCHOOL_MASTER { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<STD_MASTER> STD_MASTER { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<STUDENT_MASTER> STUDENT_MASTER { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SUBJECT_MASTER> SUBJECT_MASTER { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GALLERY_MASTER> GALLERY_MASTER { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LINK_MASTER> LINK_MASTER { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PRACTICE_PAPER> PRACTICE_PAPER { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ATTENDANCE_HDR> ATTENDANCE_HDR { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TEST_MASTER> TEST_MASTER { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<REMINDER_MASTER> REMINDER_MASTER { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<STUDENT_ANS_SHEET> STUDENT_ANS_SHEET { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HOMEWORK_MASTER> HOMEWORK_MASTER { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TODO_MASTER> TODO_MASTER { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ABOUTUS_MASTER> ABOUTUS_MASTER { get; set; }

}

}
