
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ashirvad.Repo.Model
{

using System;
    using System.Collections.Generic;
    
public partial class CIRCULAR_MASTER
{

    public long circular_id { get; set; }

    public string circular_title { get; set; }

    public string circular_description { get; set; }

    public Nullable<int> row_sta_cd { get; set; }

    public long trans_id { get; set; }

    public string file_path { get; set; }

    public string file_name { get; set; }



    public virtual TRANSACTION_MASTER TRANSACTION_MASTER { get; set; }

}

}
