//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashirvad.Repo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPETITION_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPETITION_MASTER()
        {
            this.COMPETITION_MASTER_DTL = new HashSet<COMPETITION_MASTER_DTL>();
            this.RANK_MASTER = new HashSet<RANK_MASTER>();
            this.WINNER_MASTER = new HashSet<WINNER_MASTER>();
            this.COMPETITION_RANK_MASTER = new HashSet<COMPETITION_RANK_MASTER>();
        }
    
        public long competition_id { get; set; }
        public string competition_name { get; set; }
        public double total_marks { get; set; }
        public System.DateTime competition_dt { get; set; }
        public string competition_st_time { get; set; }
        public string competition_end_time { get; set; }
        public string remarks { get; set; }
        public int row_sta_cd { get; set; }
        public long trans_id { get; set; }
        public string file_name { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
        public string extra3 { get; set; }
        public string file_path { get; set; }
        public string doc_link { get; set; }
        public Nullable<bool> doc_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPETITION_MASTER_DTL> COMPETITION_MASTER_DTL { get; set; }
        public virtual TRANSACTION_MASTER TRANSACTION_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RANK_MASTER> RANK_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WINNER_MASTER> WINNER_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPETITION_RANK_MASTER> COMPETITION_RANK_MASTER { get; set; }
    }
}
