//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashirvad.Repo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPETITION_WINNER_MASTER
    {
        public long competition_winner_id { get; set; }
        public long competition_rank_id { get; set; }
        public long competition_id { get; set; }
        public string prize_name { get; set; }
        public Nullable<int> row_sta_id { get; set; }
        public long trans_id { get; set; }
    
        public virtual COMPETITION_MASTER COMPETITION_MASTER { get; set; }
        public virtual COMPETITION_RANK_MASTER COMPETITION_RANK_MASTER { get; set; }
        public virtual TRANSACTION_MASTER TRANSACTION_MASTER { get; set; }
    }
}
