
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ashirvad.Repo.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Faculty
{

    public string name { get; set; }

    public long class_id { get; set; }

    public long course_id { get; set; }

    public long subject_id { get; set; }

    public string subject_name { get; set; }

    public string file_path { get; set; }

    public string branch_name { get; set; }

    public long faculty_id { get; set; }

}

}
