
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ashirvad.Repo.Model
{

using System;
    using System.Collections.Generic;
    
public partial class FEE_STRUCTURE_DTL
{

    public long fee_struct_dtl_id { get; set; }

    public long fee_struct_mst_id { get; set; }

    public byte[] fee_content { get; set; }

    public long trans_id { get; set; }

    public int row_sta_cd { get; set; }

    public string file_name { get; set; }

    public string file_path { get; set; }



    public virtual FEE_STRUCTURE_MASTER FEE_STRUCTURE_MASTER { get; set; }

    public virtual TRANSACTION_MASTER TRANSACTION_MASTER { get; set; }

}

}
