//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashirvad.Repo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBRARY_DATA
    {
        public long unique_id { get; set; }
        public long library_id { get; set; }
        public byte[] thumb_img_content { get; set; }
        public string thumb_img_name { get; set; }
        public string thumb_img_ext { get; set; }
        public byte[] doc_content { get; set; }
        public string doc_img_name { get; set; }
        public string doc_img_ext { get; set; }
    
        public virtual LIBRARY_MASTER LIBRARY_MASTER { get; set; }
    }
}
