//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashirvad.Repo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBRARY1_MASTER
    {
        public long library_id { get; set; }
        public string library_title { get; set; }
        public string video_link { get; set; }
        public string description { get; set; }
        public long branch_id { get; set; }
        public int row_sta_cd { get; set; }
        public long trans_id { get; set; }
        public long category_id { get; set; }
    
        public virtual BRANCH_MASTER BRANCH_MASTER { get; set; }
        public virtual CATEGORY_MASTER CATEGORY_MASTER { get; set; }
        public virtual TRANSACTION_MASTER TRANSACTION_MASTER { get; set; }
    }
}
