//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashirvad.Repo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBRARY_MASTER_DTL
    {
        public long library_dtl_id { get; set; }
        public long library_id { get; set; }
        public long branch_id { get; set; }
        public long type { get; set; }
        public byte[] library_content { get; set; }
        public string library_name { get; set; }
        public string library_filepath { get; set; }
        public int status { get; set; }
        public string remarks { get; set; }
        public int row_sta_cd { get; set; }
        public long trans_id { get; set; }
    
        public virtual BRANCH_MASTER BRANCH_MASTER { get; set; }
        public virtual LIBRARY1_MASTER LIBRARY1_MASTER { get; set; }
        public virtual TRANSACTION_MASTER TRANSACTION_MASTER { get; set; }
    }
}
