
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ashirvad.Repo.Model
{

using System;
    using System.Collections.Generic;
    
public partial class LIBRARY_STD_MASTER
{

    public long library_std_id { get; set; }

    public long library_id { get; set; }

    public Nullable<long> std_id { get; set; }



    public virtual STD_MASTER STD_MASTER { get; set; }

}

}
