//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashirvad.Repo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARKS_MASTER
    {
        public long marks_id { get; set; }
        public System.DateTime marks_dt { get; set; }
        public long test_id { get; set; }
        public long branch_id { get; set; }
        public long student_id { get; set; }
        public int batch_time_id { get; set; }
        public string file_path { get; set; }
        public string file_name { get; set; }
        public string achive_marks { get; set; }
        public int row_sta_cd { get; set; }
        public long trans_id { get; set; }
        public Nullable<long> class_dtl_id { get; set; }
        public Nullable<long> course_dtl_id { get; set; }
        public Nullable<long> subject_dtl_id { get; set; }
    
        public virtual CLASS_DTL_MASTER CLASS_DTL_MASTER { get; set; }
        public virtual COURSE_DTL_MASTER COURSE_DTL_MASTER { get; set; }
        public virtual SUBJECT_DTL_MASTER SUBJECT_DTL_MASTER { get; set; }
        public virtual TEST_MASTER TEST_MASTER { get; set; }
        public virtual STUDENT_MASTER STUDENT_MASTER { get; set; }
        public virtual BRANCH_MASTER BRANCH_MASTER { get; set; }
    }
}
