//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashirvad.Repo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATION_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NOTIFICATION_MASTER()
        {
            this.NOTIFICATION_TYPE_REL = new HashSet<NOTIFICATION_TYPE_REL>();
        }
    
        public long notif_id { get; set; }
        public Nullable<long> branch_id { get; set; }
        public string notif_message { get; set; }
        public System.DateTime notification_date { get; set; }
        public long trans_id { get; set; }
        public int row_sta_cd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICATION_TYPE_REL> NOTIFICATION_TYPE_REL { get; set; }
    }
}
