//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashirvad.Repo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATION_STD_MASTER
    {
        public long notification_std_id { get; set; }
        public long notif_id { get; set; }
        public Nullable<long> class_dtl_id { get; set; }
        public Nullable<long> course_dtl_id { get; set; }
    
        public virtual CLASS_DTL_MASTER CLASS_DTL_MASTER { get; set; }
        public virtual COURSE_DTL_MASTER COURSE_DTL_MASTER { get; set; }
        public virtual NOTIFICATION_MASTER NOTIFICATION_MASTER { get; set; }
    }
}
