//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashirvad.Repo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATION_TYPE_REL
    {
        public long unique_id { get; set; }
        public int sub_type_id { get; set; }
        public long notif_id { get; set; }
    
        public virtual NOTIFICATION_MASTER NOTIFICATION_MASTER { get; set; }
    }
}
