//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashirvad.Repo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACKAGE_RIGHTS_DTL
    {
        public long package_rights_dtl_id { get; set; }
        public long packagerights_id { get; set; }
        public long createstatus { get; set; }
        public long viewstatus { get; set; }
        public long deletestatus { get; set; }
        public long trans_id { get; set; }
        public int row_sta_cd { get; set; }
    }
}
