
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ashirvad.Repo.Model
{

using System;
    using System.Collections.Generic;
    
public partial class PRACTICE_PAPER
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PRACTICE_PAPER()
    {

        this.PRACTICE_PAPER_REL = new HashSet<PRACTICE_PAPER_REL>();

    }


    public long paper_id { get; set; }

    public long branch_id { get; set; }

    public long std_id { get; set; }

    public long sub_id { get; set; }

    public int batch_type { get; set; }

    public string remarks { get; set; }

    public int row_sta_cd { get; set; }

    public long trans_id { get; set; }



    public virtual BRANCH_MASTER BRANCH_MASTER { get; set; }

    public virtual STD_MASTER STD_MASTER { get; set; }

    public virtual SUBJECT_MASTER SUBJECT_MASTER { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PRACTICE_PAPER_REL> PRACTICE_PAPER_REL { get; set; }

}

}
