
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ashirvad.Repo.Model
{

using System;
    using System.Collections.Generic;
    
public partial class PRACTICE_PAPER_REL
{

    public long unique_id { get; set; }

    public long paper_id { get; set; }

    public string file_path { get; set; }

    public string paper_file { get; set; }



    public virtual PRACTICE_PAPER PRACTICE_PAPER { get; set; }

}

}
