//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashirvad.Repo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RANK_MASTER
    {
        public long rank_id { get; set; }
        public string rank { get; set; }
        public Nullable<long> student_id { get; set; }
        public Nullable<long> branch_id { get; set; }
        public Nullable<long> competition_id { get; set; }
        public Nullable<int> row_sta_cd { get; set; }
        public long trans_id { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
        public string extra3 { get; set; }
    
        public virtual COMPETITION_MASTER COMPETITION_MASTER { get; set; }
        public virtual TRANSACTION_MASTER TRANSACTION_MASTER { get; set; }
    }
}
