//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashirvad.Repo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class REMINDER_MASTER
    {
        public long reminder_id { get; set; }
        public long branch_id { get; set; }
        public long user_id { get; set; }
        public System.DateTime reminder_dt { get; set; }
        public string reminder_time { get; set; }
        public string reminder_desc { get; set; }
        public long trans_id { get; set; }
        public int row_sta_cd { get; set; }
    
        public virtual BRANCH_MASTER BRANCH_MASTER { get; set; }
    }
}
