//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashirvad.Repo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE_RIGHTS_MASTER
    {
        public long rolerights_id { get; set; }
        public long page_id { get; set; }
        public long role_id { get; set; }
        public bool createstatus { get; set; }
        public bool viewstatus { get; set; }
        public bool deletestatus { get; set; }
        public Nullable<int> row_sta_cd { get; set; }
        public long trans_id { get; set; }
    
        public virtual PAGE_MASTER PAGE_MASTER { get; set; }
        public virtual ROLE_MASTER ROLE_MASTER { get; set; }
    }
}
