
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ashirvad.Repo.Model
{

using System;
    using System.Collections.Generic;
    
public partial class SCHOOL_MASTER
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SCHOOL_MASTER()
    {

        this.STUDENT_MASTER = new HashSet<STUDENT_MASTER>();

    }


    public long school_id { get; set; }

    public string school_name { get; set; }

    public long branch_id { get; set; }

    public int row_sta_cd { get; set; }

    public long trans_id { get; set; }



    public virtual BRANCH_MASTER BRANCH_MASTER { get; set; }

    public virtual TRANSACTION_MASTER TRANSACTION_MASTER { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<STUDENT_MASTER> STUDENT_MASTER { get; set; }

}

}
