
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ashirvad.Repo.Model
{

using System;
    using System.Collections.Generic;
    
public partial class STUDENT_MASTER
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public STUDENT_MASTER()
    {

        this.STUDENT_MAINT = new HashSet<STUDENT_MAINT>();

        this.HOMEWORK_MASTER_DTL = new HashSet<HOMEWORK_MASTER_DTL>();

        this.STUDENT_ANS_SHEET = new HashSet<STUDENT_ANS_SHEET>();

        this.TEST_MASTER_DTL = new HashSet<TEST_MASTER_DTL>();

    }


    public long student_id { get; set; }

    public string gr_no { get; set; }

    public string first_name { get; set; }

    public string middle_name { get; set; }

    public string last_name { get; set; }

    public Nullable<System.DateTime> dob { get; set; }

    public string address { get; set; }

    public long branch_id { get; set; }

    public long std_id { get; set; }

    public Nullable<long> school_id { get; set; }

    public Nullable<int> school_time { get; set; }

    public int batch_time { get; set; }

    public Nullable<int> last_yr_result { get; set; }

    public string grade { get; set; }

    public string last_yr_class_name { get; set; }

    public string contact_no { get; set; }

    public int row_sta_cd { get; set; }

    public long trans_id { get; set; }

    public byte[] stud_img { get; set; }

    public Nullable<System.DateTime> admission_date { get; set; }



    public virtual BRANCH_MASTER BRANCH_MASTER { get; set; }

    public virtual SCHOOL_MASTER SCHOOL_MASTER { get; set; }

    public virtual STD_MASTER STD_MASTER { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<STUDENT_MAINT> STUDENT_MAINT { get; set; }

    public virtual TRANSACTION_MASTER TRANSACTION_MASTER { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HOMEWORK_MASTER_DTL> HOMEWORK_MASTER_DTL { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<STUDENT_ANS_SHEET> STUDENT_ANS_SHEET { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TEST_MASTER_DTL> TEST_MASTER_DTL { get; set; }

}

}
