
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ashirvad.Repo.Model
{

using System;
    using System.Collections.Generic;
    
public partial class STUDENT_PAYMENT_REL
{

    public long payment_rel_id { get; set; }

    public long payment_id { get; set; }

    public byte[] payment_content { get; set; }

    public string file_name { get; set; }

    public int row_sta_cd { get; set; }

    public long trans_id { get; set; }



    public virtual STUDENT_PAYMENT_MASTER STUDENT_PAYMENT_MASTER { get; set; }

    public virtual TRANSACTION_MASTER TRANSACTION_MASTER { get; set; }

}

}
