
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ashirvad.Repo.Model
{

using System;
    using System.Collections.Generic;
    
public partial class STUDENT_MAINT
{

    public long parent_id { get; set; }

    public long student_id { get; set; }

    public string parent_name { get; set; }

    public string father_occupation { get; set; }

    public string mother_occupation { get; set; }

    public string contact_no { get; set; }



    public virtual STUDENT_MASTER STUDENT_MASTER { get; set; }

}

}
