//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashirvad.Repo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_PAYMENT_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT_PAYMENT_MASTER()
        {
            this.STUDENT_PAYMENT_REL = new HashSet<STUDENT_PAYMENT_REL>();
        }
    
        public long payment_id { get; set; }
        public long student_id { get; set; }
        public int status_id { get; set; }
        public string admin_remark { get; set; }
        public string student_remark { get; set; }
        public long trans_id { get; set; }
        public int row_sta_cd { get; set; }
        public long branch_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_PAYMENT_REL> STUDENT_PAYMENT_REL { get; set; }
        public virtual BRANCH_MASTER BRANCH_MASTER { get; set; }
    }
}
