
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ashirvad.Repo.Model
{

using System;
    using System.Collections.Generic;
    
public partial class TEST_PAPER_REL
{

    public long test_paper_id { get; set; }

    public long test_id { get; set; }

    public int paper_type { get; set; }

    public byte[] doc_content { get; set; }

    public string doc_link { get; set; }

    public string remakrs { get; set; }

    public int row_sta_cd { get; set; }

    public long trans_id { get; set; }

    public string file_name { get; set; }



    public virtual TEST_MASTER TEST_MASTER { get; set; }

}

}
