
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ashirvad.Repo.Model
{

using System;
    using System.Collections.Generic;
    
public partial class TODO_MASTER
{

    public long todo_id { get; set; }

    public System.DateTime todo_dt { get; set; }

    public long branch_id { get; set; }

    public long user_id { get; set; }

    public string todo_desc { get; set; }

    public byte[] todo_doc_content { get; set; }

    public string todo_doc_name { get; set; }

    public int row_sta_cd { get; set; }

    public long trans_id { get; set; }

    public Nullable<bool> reg_status { get; set; }

    public string remark { get; set; }



    public virtual BRANCH_MASTER BRANCH_MASTER { get; set; }

}

}
