//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashirvad.Repo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_DESC
    {
        public int @class { get; set; }
        public int type { get; set; }
        public string short_desc { get; set; }
        public string long_desc { get; set; }
        public string row_sta_cd { get; set; }
    }
}
