var commonData =
{
    siteURL: $("#hdnFldSiteURL").val(),
    VDName: $("#hdnFldVDName").val(),
    BranchID: $("#hdnBranchID").val(),
    Branch: $("#hdnFldVDName").val() + "Branch/",
    Login: $("#hdnFldVDName").val() + "Login/",
    School: $("#hdnFldVDName").val() + "School/",
    Batch: $("#hdnFldVDName").val() + "Batch/",
    Standard: $("#hdnFldVDName").val() + "Standard/",
    Subject: $("#hdnFldVDName").val() + "Subject/",
    User: $("#hdnFldVDName").val() + "User/",
    Student: $("#hdnFldVDName").val() + "Student/",
    ManageStudent: $("#hdnFldVDName").val() + "ManageStudent/",
    Notification: $("#hdnFldVDName").val() + "Notification/",
    Photos: $("#hdnFldVDName").val() + "Photos/",
    Videos: $("#hdnFldVDName").val() + "Videos/",
    LiveVideo: $("#hdnFldVDName").val() + "LiveVideo/",
    Youtube: $("#hdnFldVDName").val() + "Youtube/",
    Banner: $("#hdnFldVDName").val() + "Banner/",
    Paper: $("#hdnFldVDName").val() + "Papers/",
    Library: $("#hdnFldVDName").val() + "Library/",
    UserPermission: $("#hdnFldVDName").val() + "UserPermission/",
    AttendanceEntry: $("#hdnFldVDName").val() + "AttendanceEntry/",
    AttendanceRegister: $("#hdnFldVDName").val() + "AttendanceRegister/",
    TestPaper: $("#hdnFldVDName").val() + "TestPaper/",
    Homework: $("#hdnFldVDName").val() + "Homework/",
    Reminder: $("#hdnFldVDName").val() + "Reminder/",
    ToDo: $("#hdnFldVDName").val() + "ToDo/",
    ToDoRegister: $("#hdnFldVDName").val() + "ToDoRegister/",
};